Algoritmo "XP5"

Var

numero: real

Inicio

Escreval ("Digite um número aleátorio!")
Escreva ("Digite aqui: ")
Leia (numero)

Se (numero = 0) entao
   Escreval ("")
   Escreva ("O número digitado é nulo!")
senao
     Se (numero > 0) entao
     Escreval ("")
     Escreva ("O número digitado é maior que 0!")
     senao
          Se (numero < 0) entao
          Escreval ("")
          Escreva ("O número digitado é menor que 0!")
          Fimse
     Fimse
Fimse


Fimalgoritmo